import React from 'react'
import { motion, useInView, useScroll, useSpring, useTransform } from "motion/react"


const ScrollAnimations = () => {

    //scrollYProgress: Sayfanın ne kadar kaydırıldığını takip eder.

    //scrollYProgress: Sayfanın en üstünden en altına kadar olan mesafeyi 0 ile 1 arasında bir sayıya dönüştürür.

    //Çalışma Mantığı: Sayfanın en üstündeyken değer 0'dır. Tam ortaya geldiğinde 0.5, en alta indiğinde ise 1 olur. Bu sayı sürekli güncellenen bir "canlı değer"dir (MotionValue).
    const { scrollYProgress } = useScroll();


    //Gelen ham sayısal değeri (0-1 arası) alır ve ona fiziksel bir yumuşaklık (yaylanma efekti) ekler.
    const scaleX = useSpring(scrollYProgress);


    //bir sayı aralığını başka bir aralığa (veya renge) "haritalamak" için kullanılır. Bir nevi çevirmendir.
    
    const background = useTransform(
        scrollYProgress,
        [0,1],
        ["rgb(86,1,245)", "rgb(1, 245, 13"]
    )

  return (
    <>
    <motion.div
    style={{
        scaleX,
        background,
        transformOrigin: "left",
        position: "sticky",
        top: 5,
        width: "100%",
        height: "20px"
    }}
        />

        <div style={{ maxWidth: "700px", margin: "auto"}}>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi eligendi soluta minima, pariatur suscipit, numquam beatae odit officiis reiciendis nam aperiam fugit? Dignissimos neque illo ea rerum blanditiis nihil unde officiis, impedit eveniet corporis quaerat ad nulla suscipit a tenetur nisi debitis veritatis? Tempora tempore sed amet facilis corporis voluptate nam unde consectetur, quasi, reiciendis aspernatur laboriosam doloribus itaque dolorem explicabo, reprehenderit necessitatibus. Architecto sit totam modi a non possimus, commodi incidunt ea ut impedit! Obcaecati, dicta praesentium ad quo expedita aut ratione officiis, quia eum placeat culpa magnam voluptatem neque quod tempore incidunt sit maiores minima illo! Rerum exercitationem sunt amet! Quos eligendi sint laboriosam nihil omnis labore repellat aperiam libero. Debitis, in cupiditate unde eos commodi accusamus nulla dolores ipsa corrupti eaque voluptatem hic vel est distinctio veniam? Est esse harum, similique sit sapiente quibusdam in velit asperiores praesentium ipsam magnam quos natus ducimus magni doloribus laborum repudiandae.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi eligendi soluta minima, pariatur suscipit, numquam beatae odit officiis reiciendis nam aperiam fugit? Dignissimos neque illo ea rerum blanditiis nihil unde officiis, impedit eveniet corporis quaerat ad nulla suscipit a tenetur nisi debitis veritatis? Tempora tempore sed amet facilis corporis voluptate nam unde consectetur, quasi, reiciendis aspernatur laboriosam doloribus itaque dolorem explicabo, reprehenderit necessitatibus. Architecto sit totam modi a non possimus, commodi incidunt ea ut impedit! Obcaecati, dicta praesentium ad quo expedita aut ratione officiis, quia eum placeat culpa magnam voluptatem neque quod tempore incidunt sit maiores minima illo! Rerum exercitationem sunt amet! Quos eligendi sint laboriosam nihil omnis labore repellat aperiam libero. Debitis, in cupiditate unde eos commodi accusamus nulla dolores ipsa corrupti eaque voluptatem hic vel est distinctio veniam? Est esse harum, similique sit sapiente quibusdam in velit asperiores praesentium ipsam magnam quos natus ducimus magni doloribus laborum repudiandae.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi eligendi soluta minima, pariatur suscipit, numquam beatae odit officiis reiciendis nam aperiam fugit? Dignissimos neque illo ea rerum blanditiis nihil unde officiis, impedit eveniet corporis quaerat ad nulla suscipit a tenetur nisi debitis veritatis? Tempora tempore sed amet facilis corporis voluptate nam unde consectetur, quasi, reiciendis aspernatur laboriosam doloribus itaque dolorem explicabo, reprehenderit necessitatibus. Architecto sit totam modi a non possimus, commodi incidunt ea ut impedit! Obcaecati, dicta praesentium ad quo expedita aut ratione officiis, quia eum placeat culpa magnam voluptatem neque quod tempore incidunt sit maiores minima illo! Rerum exercitationem sunt amet! Quos eligendi sint laboriosam nihil omnis labore repellat aperiam libero. Debitis, in cupiditate unde eos commodi accusamus nulla dolores ipsa corrupti eaque voluptatem hic vel est distinctio veniam? Est esse harum, similique sit sapiente quibusdam in velit asperiores praesentium ipsam magnam quos natus ducimus magni doloribus laborum repudiandae.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi eligendi soluta minima, pariatur suscipit, numquam beatae odit officiis reiciendis nam aperiam fugit? Dignissimos neque illo ea rerum blanditiis nihil unde officiis, impedit eveniet corporis quaerat ad nulla suscipit a tenetur nisi debitis veritatis? Tempora tempore sed amet facilis corporis voluptate nam unde consectetur, quasi, reiciendis aspernatur laboriosam doloribus itaque dolorem explicabo, reprehenderit necessitatibus. Architecto sit totam modi a non possimus, commodi incidunt ea ut impedit! Obcaecati, dicta praesentium ad quo expedita aut ratione officiis, quia eum placeat culpa magnam voluptatem neque quod tempore incidunt sit maiores minima illo! Rerum exercitationem sunt amet! Quos eligendi sint laboriosam nihil omnis labore repellat aperiam libero. Debitis, in cupiditate unde eos commodi accusamus nulla dolores ipsa corrupti eaque voluptatem hic vel est distinctio veniam? Est esse harum, similique sit sapiente quibusdam in velit asperiores praesentium ipsam magnam quos natus ducimus magni doloribus laborum repudiandae.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi eligendi soluta minima, pariatur suscipit, numquam beatae odit officiis reiciendis nam aperiam fugit? Dignissimos neque illo ea rerum blanditiis nihil unde officiis, impedit eveniet corporis quaerat ad nulla suscipit a tenetur nisi debitis veritatis? Tempora tempore sed amet facilis corporis voluptate nam unde consectetur, quasi, reiciendis aspernatur laboriosam doloribus itaque dolorem explicabo, reprehenderit necessitatibus. Architecto sit totam modi a non possimus, commodi incidunt ea ut impedit! Obcaecati, dicta praesentium ad quo expedita aut ratione officiis, quia eum placeat culpa magnam voluptatem neque quod tempore incidunt sit maiores minima illo! Rerum exercitationem sunt amet! Quos eligendi sint laboriosam nihil omnis labore repellat aperiam libero. Debitis, in cupiditate unde eos commodi accusamus nulla dolores ipsa corrupti eaque voluptatem hic vel est distinctio veniam? Est esse harum, similique sit sapiente quibusdam in velit asperiores praesentium ipsam magnam quos natus ducimus magni doloribus laborum repudiandae.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi eligendi soluta minima, pariatur suscipit, numquam beatae odit officiis reiciendis nam aperiam fugit? Dignissimos neque illo ea rerum blanditiis nihil unde officiis, impedit eveniet corporis quaerat ad nulla suscipit a tenetur nisi debitis veritatis? Tempora tempore sed amet facilis corporis voluptate nam unde consectetur, quasi, reiciendis aspernatur laboriosam doloribus itaque dolorem explicabo, reprehenderit necessitatibus. Architecto sit totam modi a non possimus, commodi incidunt ea ut impedit! Obcaecati, dicta praesentium ad quo expedita aut ratione officiis, quia eum placeat culpa magnam voluptatem neque quod tempore incidunt sit maiores minima illo! Rerum exercitationem sunt amet! Quos eligendi sint laboriosam nihil omnis labore repellat aperiam libero. Debitis, in cupiditate unde eos commodi accusamus nulla dolores ipsa corrupti eaque voluptatem hic vel est distinctio veniam? Est esse harum, similique sit sapiente quibusdam in velit asperiores praesentium ipsam magnam quos natus ducimus magni doloribus laborum repudiandae.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi eligendi soluta minima, pariatur suscipit, numquam beatae odit officiis reiciendis nam aperiam fugit? Dignissimos neque illo ea rerum blanditiis nihil unde officiis, impedit eveniet corporis quaerat ad nulla suscipit a tenetur nisi debitis veritatis? Tempora tempore sed amet facilis corporis voluptate nam unde consectetur, quasi, reiciendis aspernatur laboriosam doloribus itaque dolorem explicabo, reprehenderit necessitatibus. Architecto sit totam modi a non possimus, commodi incidunt ea ut impedit! Obcaecati, dicta praesentium ad quo expedita aut ratione officiis, quia eum placeat culpa magnam voluptatem neque quod tempore incidunt sit maiores minima illo! Rerum exercitationem sunt amet! Quos eligendi sint laboriosam nihil omnis labore repellat aperiam libero. Debitis, in cupiditate unde eos commodi accusamus nulla dolores ipsa corrupti eaque voluptatem hic vel est distinctio veniam? Est esse harum, similique sit sapiente quibusdam in velit asperiores praesentium ipsam magnam quos natus ducimus magni doloribus laborum repudiandae.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi eligendi soluta minima, pariatur suscipit, numquam beatae odit officiis reiciendis nam aperiam fugit? Dignissimos neque illo ea rerum blanditiis nihil unde officiis, impedit eveniet corporis quaerat ad nulla suscipit a tenetur nisi debitis veritatis? Tempora tempore sed amet facilis corporis voluptate nam unde consectetur, quasi, reiciendis aspernatur laboriosam doloribus itaque dolorem explicabo, reprehenderit necessitatibus. Architecto sit totam modi a non possimus, commodi incidunt ea ut impedit! Obcaecati, dicta praesentium ad quo expedita aut ratione officiis, quia eum placeat culpa magnam voluptatem neque quod tempore incidunt sit maiores minima illo! Rerum exercitationem sunt amet! Quos eligendi sint laboriosam nihil omnis labore repellat aperiam libero. Debitis, in cupiditate unde eos commodi accusamus nulla dolores ipsa corrupti eaque voluptatem hic vel est distinctio veniam? Est esse harum, similique sit sapiente quibusdam in velit asperiores praesentium ipsam magnam quos natus ducimus magni doloribus laborum repudiandae.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi eligendi soluta minima, pariatur suscipit, numquam beatae odit officiis reiciendis nam aperiam fugit? Dignissimos neque illo ea rerum blanditiis nihil unde officiis, impedit eveniet corporis quaerat ad nulla suscipit a tenetur nisi debitis veritatis? Tempora tempore sed amet facilis corporis voluptate nam unde consectetur, quasi, reiciendis aspernatur laboriosam doloribus itaque dolorem explicabo, reprehenderit necessitatibus. Architecto sit totam modi a non possimus, commodi incidunt ea ut impedit! Obcaecati, dicta praesentium ad quo expedita aut ratione officiis, quia eum placeat culpa magnam voluptatem neque quod tempore incidunt sit maiores minima illo! Rerum exercitationem sunt amet! Quos eligendi sint laboriosam nihil omnis labore repellat aperiam libero. Debitis, in cupiditate unde eos commodi accusamus nulla dolores ipsa corrupti eaque voluptatem hic vel est distinctio veniam? Est esse harum, similique sit sapiente quibusdam in velit asperiores praesentium ipsam magnam quos natus ducimus magni doloribus laborum repudiandae.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi eligendi soluta minima, pariatur suscipit, numquam beatae odit officiis reiciendis nam aperiam fugit? Dignissimos neque illo ea rerum blanditiis nihil unde officiis, impedit eveniet corporis quaerat ad nulla suscipit a tenetur nisi debitis veritatis? Tempora tempore sed amet facilis corporis voluptate nam unde consectetur, quasi, reiciendis aspernatur laboriosam doloribus itaque dolorem explicabo, reprehenderit necessitatibus. Architecto sit totam modi a non possimus, commodi incidunt ea ut impedit! Obcaecati, dicta praesentium ad quo expedita aut ratione officiis, quia eum placeat culpa magnam voluptatem neque quod tempore incidunt sit maiores minima illo! Rerum exercitationem sunt amet! Quos eligendi sint laboriosam nihil omnis labore repellat aperiam libero. Debitis, in cupiditate unde eos commodi accusamus nulla dolores ipsa corrupti eaque voluptatem hic vel est distinctio veniam? Est esse harum, similique sit sapiente quibusdam in velit asperiores praesentium ipsam magnam quos natus ducimus magni doloribus laborum repudiandae.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi eligendi soluta minima, pariatur suscipit, numquam beatae odit officiis reiciendis nam aperiam fugit? Dignissimos neque illo ea rerum blanditiis nihil unde officiis, impedit eveniet corporis quaerat ad nulla suscipit a tenetur nisi debitis veritatis? Tempora tempore sed amet facilis corporis voluptate nam unde consectetur, quasi, reiciendis aspernatur laboriosam doloribus itaque dolorem explicabo, reprehenderit necessitatibus. Architecto sit totam modi a non possimus, commodi incidunt ea ut impedit! Obcaecati, dicta praesentium ad quo expedita aut ratione officiis, quia eum placeat culpa magnam voluptatem neque quod tempore incidunt sit maiores minima illo! Rerum exercitationem sunt amet! Quos eligendi sint laboriosam nihil omnis labore repellat aperiam libero. Debitis, in cupiditate unde eos commodi accusamus nulla dolores ipsa corrupti eaque voluptatem hic vel est distinctio veniam? Est esse harum, similique sit sapiente quibusdam in velit asperiores praesentium ipsam magnam quos natus ducimus magni doloribus laborum repudiandae.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi eligendi soluta minima, pariatur suscipit, numquam beatae odit officiis reiciendis nam aperiam fugit? Dignissimos neque illo ea rerum blanditiis nihil unde officiis, impedit eveniet corporis quaerat ad nulla suscipit a tenetur nisi debitis veritatis? Tempora tempore sed amet facilis corporis voluptate nam unde consectetur, quasi, reiciendis aspernatur laboriosam doloribus itaque dolorem explicabo, reprehenderit necessitatibus. Architecto sit totam modi a non possimus, commodi incidunt ea ut impedit! Obcaecati, dicta praesentium ad quo expedita aut ratione officiis, quia eum placeat culpa magnam voluptatem neque quod tempore incidunt sit maiores minima illo! Rerum exercitationem sunt amet! Quos eligendi sint laboriosam nihil omnis labore repellat aperiam libero. Debitis, in cupiditate unde eos commodi accusamus nulla dolores ipsa corrupti eaque voluptatem hic vel est distinctio veniam? Est esse harum, similique sit sapiente quibusdam in velit asperiores praesentium ipsam magnam quos natus ducimus magni doloribus laborum repudiandae.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi eligendi soluta minima, pariatur suscipit, numquam beatae odit officiis reiciendis nam aperiam fugit? Dignissimos neque illo ea rerum blanditiis nihil unde officiis, impedit eveniet corporis quaerat ad nulla suscipit a tenetur nisi debitis veritatis? Tempora tempore sed amet facilis corporis voluptate nam unde consectetur, quasi, reiciendis aspernatur laboriosam doloribus itaque dolorem explicabo, reprehenderit necessitatibus. Architecto sit totam modi a non possimus, commodi incidunt ea ut impedit! Obcaecati, dicta praesentium ad quo expedita aut ratione officiis, quia eum placeat culpa magnam voluptatem neque quod tempore incidunt sit maiores minima illo! Rerum exercitationem sunt amet! Quos eligendi sint laboriosam nihil omnis labore repellat aperiam libero. Debitis, in cupiditate unde eos commodi accusamus nulla dolores ipsa corrupti eaque voluptatem hic vel est distinctio veniam? Est esse harum, similique sit sapiente quibusdam in velit asperiores praesentium ipsam magnam quos natus ducimus magni doloribus laborum repudiandae.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi eligendi soluta minima, pariatur suscipit, numquam beatae odit officiis reiciendis nam aperiam fugit? Dignissimos neque illo ea rerum blanditiis nihil unde officiis, impedit eveniet corporis quaerat ad nulla suscipit a tenetur nisi debitis veritatis? Tempora tempore sed amet facilis corporis voluptate nam unde consectetur, quasi, reiciendis aspernatur laboriosam doloribus itaque dolorem explicabo, reprehenderit necessitatibus. Architecto sit totam modi a non possimus, commodi incidunt ea ut impedit! Obcaecati, dicta praesentium ad quo expedita aut ratione officiis, quia eum placeat culpa magnam voluptatem neque quod tempore incidunt sit maiores minima illo! Rerum exercitationem sunt amet! Quos eligendi sint laboriosam nihil omnis labore repellat aperiam libero. Debitis, in cupiditate unde eos commodi accusamus nulla dolores ipsa corrupti eaque voluptatem hic vel est distinctio veniam? Est esse harum, similique sit sapiente quibusdam in velit asperiores praesentium ipsam magnam quos natus ducimus magni doloribus laborum repudiandae.</p>
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Modi eligendi soluta minima, pariatur suscipit, numquam beatae odit officiis reiciendis nam aperiam fugit? Dignissimos neque illo ea rerum blanditiis nihil unde officiis, impedit eveniet corporis quaerat ad nulla suscipit a tenetur nisi debitis veritatis? Tempora tempore sed amet facilis corporis voluptate nam unde consectetur, quasi, reiciendis aspernatur laboriosam doloribus itaque dolorem explicabo, reprehenderit necessitatibus. Architecto sit totam modi a non possimus, commodi incidunt ea ut impedit! Obcaecati, dicta praesentium ad quo expedita aut ratione officiis, quia eum placeat culpa magnam voluptatem neque quod tempore incidunt sit maiores minima illo! Rerum exercitationem sunt amet! Quos eligendi sint laboriosam nihil omnis labore repellat aperiam libero. Debitis, in cupiditate unde eos commodi accusamus nulla dolores ipsa corrupti eaque voluptatem hic vel est distinctio veniam? Est esse harum, similique sit sapiente quibusdam in velit asperiores praesentium ipsam magnam quos natus ducimus magni doloribus laborum repudiandae.</p>
        </div>
    </>

        
  )
}

export default ScrollAnimations